#ifndef PROJECTMCODES_GFSCENEMANAGER_H
#define PROJECTMCODES_GFSCENEMANAGER_H


struct gfSceneManager {

};

#define GF_SCENE_MANAGER ((gfSceneManager*) 0x8002d018)

#endif //PROJECTMCODES_GFSCENEMANAGER_H
