//
// Created by johno on 6/26/2020.
//

#ifndef CSSCUSTOMCONTROLS_MUSELCTCHRNAMEENTRY_H
#define CSSCUSTOMCONTROLS_MUSELCTCHRNAMEENTRY_H


struct MuSelctChrNameEntry {

};


#endif //CSSCUSTOMCONTROLS_MUSELCTCHRNAMEENTRY_H
