name: Brawlback Kit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get install cmake build-essential

    - name: Configure CMake
      run: |
           export DEVKITPPC=/opt/devkitpro/devkitPPC
           cmake -B build/ -S . -DCMAKE_TOOLCHAIN_FILE=./CMake/PPCToolchain.cmake -DBRAWLBACK=1

    - name: Build
      # Build your program with the given configuration
      run: cmake --build build/
