name: Brawlback Kit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    
    - name: Install Dependencies
      run: |
           sudo apt-get update
           sudo apt-get install cmake build-essential -y

    - name: Configure CMake
      run: |
           export DEVKITPPC=/opt/devkitpro/devkitPPC
           cmake -B build/ -S . -DCMAKE_TOOLCHAIN_FILE=CMake/PPCToolchain.cmake -DBRAWLBACK=1

    - name: Build
      run: cmake --build build/
