name: Brawlback Syriinge

on:
  push:
    branches: [ "syriinge" ]
  pull_request:
    branches: [ "syriinge" ]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container: 
      image: devkitpro/devkitppc:latest
      options: --user root
    steps:
    - name: Setup LFS
      run: sudo apt-get install git-lfs -y
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup Tools
      run: |
           chmod +x "./tools/Clang/Ubuntu/clang"
           chmod +x "./tools/Clang/Ubuntu/ld.lld"
    - name: Build
      run: make linux
    - name: "Package"
      if: success()
      working-directory: ${{ github.workspace }}
      run: |
           mkdir SDCard
           mv "Brawlback-Online.rel" "./SDCard"
           mkdir artifact
           FILE_NAME=Brawlback-Online.zip
           zip -r "${FILE_NAME}" "./SDCard"
           mv "${FILE_NAME}" ./artifact/
    - name: "Publish"
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: "Brawlback-Online"
        path: "./artifact/"
