name: Brawlback Syriinge

on:
  push:
    branches: [ "syriinge" ]
  pull_request:
    branches: [ "syriinge" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Pull recursive submodules
      run: git submodule update --init --recursive
    - name: Build
      run: make linux
    - name: "Package"
      if: success()
      working-directory: ${{ github.workspace }}
      run: |
           mkdir SDCard
           mv "Brawlback-Online.rel" "./SDCard"
           mkdir artifact
           FILE_NAME=${{ env.CURR_DATE }}-${{ env.GIT_HASH }}.zip
           zip -r "${FILE_NAME}" "./SDCard"
           mv "${FILE_NAME}" ./artifact/
           
    - name: "Publish"
      if: success()
      uses: actions/upload-artifact@v2-preview
      with:
        name: "Brawlback-Online"
        path: "./artifact/"
